#!perl
use v5.16;
use warnings;

use App::tldr;
App::tldr->new->parse_options(@ARGV)->run;

__END__

=head1 NAME

tldr - a perl tldr client

=head1 SYNOPSIS

  Usage: tldr [command]

  Options:
   -o, --os=OS         os (osx, sunos or linux)
   -l, --language=lang use other language
   -h, --help          show this help
   -v, --version       show version
       --pager=CMD     specify pager command
       --no-pager      turn off paging
       --unicode       use fancy unicode characters (defaults to true if LANG =~ /UTF-8/)
       --no-unicode    do not use unicode characters

  Environment variables:
   * TLDR_REPOSITORY=/path/to/tldr-pages/tldr
       by default, tldr get man pages from https://github.com/tldr-pages/tldr
       If you set a local tldr's repository, you'll see man pages quickly.
   * TLDR_DEBUG=1
       turn on debug message

  Examples:
   $ tldr tar
   $ tldr -l zh tar
   $ tldr -o osx brew
   $ TLDR_REPOSITORY=/path/to/tldr-pages/tldr tldr gzip

=head1 SEE ALSO

L<https://github.com/tldr-pages/tldr>
